### ISSUE TITLE
Parens surrounded by large black boxes in org babel

### ISSUE THREAD

**Issue by chookity-pokk** [sashimacs/os1-theme#2]
I have three screenshots below, the first is my default theme which shows parens normally and the second is the os1 theme which has parens with these black boxes surrounding them. It seems like regular programming files are just fine, but org babel blocks have the issue. 

I also have a third screenshot which shows parts of a babel block being fine, but then having the random blocks. Not really sure what the issue is because it seems a bit random. 

![paren-no-issues](https://user-images.githubusercontent.com/24358100/231192577-c21d91e0-9aec-4692-9576-0dbb6e178028.png)
![os1-theme-paren-issues](https://user-images.githubusercontent.com/24358100/231192601-98001315-f85a-4e14-bbd5-aa8b5a11684c.png)
![babel-paren-small-issue](https://user-images.githubusercontent.com/24358100/231192617-7f9184ba-f2d9-4cd1-8fa7-31f5b69821c8.png)

**Comment by sashimacs** [comment]
I believe that face is `rainbow-delimiters-unmatched-face` (you can check with `M-x describe-face`). Weird though because it's showing up with valid matches. Can you check `M-x list-faces-display` and look at the `rainbow-delimiters` faces? Should look something like this:

![Screenshot 2023-04-11 at 10 58 37 AM](https://user-images.githubusercontent.com/130169373/231203824-3473aaff-745f-4333-a324-ea79254f5e4a.png)

This could be related to the other issue where it seems like another theme is getting applied before and overwriting some settings (in this case probably the `:background` attribute of some faces.

**Comment by chookity-pokk** [comment]
It seems as though mine look roughly the same,

![image](https://user-images.githubusercontent.com/24358100/231303202-f0a2c7ac-c50e-4420-97fd-72c4ac9c78b8.png)

**Comment by sashimacs** [comment]
The theme was just re-written to use autothemer instead of building off solarized, can you try it out and see if it fixes your problem?

**Comment by chookity-pokk** [comment]
Sorry for the delayed response, this past week has been hectic with classes and whatnot. It seems to have been fixed though so I'm going to close this issue. Thank you very much!
