### ISSUE TITLE
Path highlighting blocks words from being readable

### ISSUE THREAD

**Issue by chookity-pokk** [sashimacs/os1-theme#3]
In the screenshot below you can see that whatever item I am hovering over is entirely blocked out. I think the font change doesn't have enough contrast to make it readable. 

![os1-path-issues](https://user-images.githubusercontent.com/24358100/231194334-77b674be-84c5-4ddc-b2c6-8ad59e4cb9a9.png)

**Comment by sashimacs** [comment]
I think something strange is going on because the find-file background should match default background, not that light-grey color. Are you loading another theme before calling `(load-theme 'os1 t)`? It seems like some colors are coming through but some are being overwritten.

![Screenshot 2023-04-11 at 10 44 35 AM](https://user-images.githubusercontent.com/130169373/231199646-19be8d43-27bc-4c5a-a2f1-9ebba2bd20ff.png)

**Comment by chookity-pokk** [comment]
I think you're right because my laptop isn't having that problem. I'll close this now and report back once I figure out the issue.
